### PR TITLE
MSVC build fix

### PR DESCRIPTION
**Pull request by fabiencastan**
To avoid this error:
```
Bresenham.obj : error LNK2019: unresolved external symbol "int __cdecl boost::math::sign<int>(int const &)" (??$sign@H@math@boost@@YAHAEBH@Z) referenced in function "class cctag::EdgePoint * __cdecl cctag::gradientDirectionDescent(class
 cctag::EdgePointCollection const &,class cctag::EdgePoint const &,int,unsigned __int64,class cv::Mat const &,class cv::Mat const &,int)" (?gradientDirectionDescent@cctag@@YAPEAVEdgePoint@1@AEBVEdgePointCollection@1@AEBV21@H_KAEBVMat@cv
@@3H@Z) [D:\release\CCTag\build-bundle\src\CCTag.vcxproj]
Bresenham.obj : error LNK2019: unresolved external symbol "int __cdecl boost::math::sign<float>(float const &)" (??$sign@M@math@boost@@YAHAEBM@Z) referenced in function "class cctag::EdgePoint * __cdecl cctag::gradientDirectionDescent(c
lass cctag::EdgePointCollection const &,class cctag::EdgePoint const &,int,unsigned __int64,class cv::Mat const &,class cv::Mat const &,int)" (?gradientDirectionDescent@cctag@@YAPEAVEdgePoint@1@AEBVEdgePointCollection@1@AEBV21@H_KAEBVMa
t@cv@@3H@Z) [D:\release\CCTag\build-bundle\src\CCTag.vcxproj]
D:\release\CCTag\build-bundle\Windows-AMD64\Release\CCTag.dll : fatal error LNK1120: 2 unresolved externals [D:\release\CCTag\build-bundle\src\CCTag.vcxproj]
P
```

### CODE REVIEW

**Comment by simogasp** [comment]
Can you also post the compilation error message, just for reference?
And which version of boost? Cause on vcpkg they use 1.76 and everything was ok

**Comment by fabiencastan** [comment]
I was using latest version of vcpkg with boost-1.76 and VS 2019.
I don't have the log anymore.

**Comment by fabiencastan** [comment]
Log of the error added to the description.

**Review by simogasp — APPROVED** [review]
LGTM

**Pull request merged**
