### PR TITLE
Update Cuda Cub

### PR DESCRIPTION
**Pull request by fabiencastan**
And use git sub-module instead of hard-copy.

### CODE REVIEW

**Comment by fabiencastan** [comment]
@griwodz

If we enable GPU support, we currently have an error only on windows which says: "uses too much shared data" due to `thrust::sort`.

If we update CUB to the latest version (as tested in this PR), we get the same error on Windows and Linux. So in this PR, we can see the error message on Travis.

**Comment by griwodz** [comment]
I have circumvented the problem by copying the entire list to host and used thrust::sort on the host. That wastes time and I'm going to look for something better. But it should fix the CUB update problem for now.

**Comment by griwodz** [comment]
This PR removes some old CUB code that was needed for a few combinations or card and SDK. I think the GTX 980 with SDK 7.5 crashed on the Thrust uniq() function. I don't have access to a 980 right now.

**Comment by griwodz** [comment]
I propose to abandon this PR in favour of #110

**Pull request closed without merging**
