### PR TITLE
[cuda] fix CCTAG_NO_THRUST_COPY_IF code

### PR DESCRIPTION
**Pull request by simogasp**
I guess we merged #110 too quickly :-)

* c++ comment symbol :-)

* conditional include

* `=` replaced by `-` (@griwodz can u confirm?)

### CODE REVIEW

**Comment by griwodz** [comment]
Uff !
Yes. That is an annoying bug. Did that ever work? Why and how???

**Comment by simogasp** [comment]
when using `./Linux-x86_64/detection -i 0 -n 3 --use-cuda`  (video mode)

it fails:
```
Starting to read video frames
Creating TagPipe 0
Initializing TagPipe 0
Loading image 0 into TagPipe 0
~/dev/alicevision/sandbox/CCTag/src/cctag/cuda/debug_macros.cpp:78~dev/alicevision/sandbox/CCTag/src/cctag/cuda/debug_macros.cpp:78
    called from ~/dev/alicevision/sandbox/CCTag/src/./cctag/cuda/frame_07b_vote_sort_uniq_thrust.cu:44
    cudaStreamSynchronize failed: driver shutting down
    called from ~/dev/alicevision/sandbox/CCTag/src/./cctag/cuda/frame_04_hyst.cuterminate called after throwing an instance of '
:384
    cudaStreamSynchronize failed: thrust::system::system_error'
driver shutting down
free(): corrupted unsorted chunks
  what():  get_max_shared_memory_per_block :failed to cudaGetDevice: cudaErrorCudartUnloading: driver shutting down
Aborted (core dumped)
```

**Comment by simogasp** [comment]
"interestingly" it fails with different errors every time:
```
Starting to read video frames
Creating TagPipe 0
Initializing TagPipe 0
Loading image 0 into TagPipe 0
~dev/alicevision/sandbox/CCTag/src/./cctag/cuda/frame_alloc.cu:155
~/dev/alicevision/sandbox/CCTag/src/./cctag/cuda/frame_alloc.cu:155
    cudaMemsetAsync failed:     ~/dev/alicevision/sandbox/CCTag/src/./cctag/cuda/frame_alloc.cu:155
    cudaMemsetAsync failed: driver shutting down
driver shutting down
cudaMemsetAsync failed: driver shutting down
free(): corrupted unsorted chunks
Segmentation fault (core dumped)
```
or
```
Starting to read video frames
Creating TagPipe 0
Initializing TagPipe 0
Loading image 0 into TagPipe 0
~/dev/alicevision/sandbox/CCTag/src/./cctag/cuda/framemeta.cu:terminate called after throwing an instance of 'thrust::system::system_error'
121
    Could not copy int variable to device symbol: driver shutting down
  what():  get_max_shared_memory_per_block :failed to cudaGetDevice: cudaErrorCudartUnloading: driver shutting down
Aborted (core dumped)
```
or
```
Starting to read video frames
Creating TagPipe 0
Initializing TagPipe 0
Loading image 0 into TagPipe 0
Segmentation fault (core dumped)
```
The card is RTX 2080

**Comment by griwodz** [comment]
Well, it makes sense that the bug is random because the number in size is random.

**Comment by griwodz** [comment]
So, it would have copied random but probably large portions of GPU memory into random large portions of CPU memory using DMA. A debugger would be unable to catch it because it's out of CPU control.

**Comment by simogasp** [comment]
@griwodz is there a quick fix for this or does it requires some work?
We can merge the PR and open a related issue in case

**Comment by griwodz** [comment]
@simogasp You mean a quick fix for the original Thrust problem? No, this is still the solution until we stop using Thrust for memory allocation.

**Comment by simogasp** [comment]
no i meant a quick fix for the Segmentation fault problem

**Comment by griwodz** [comment]
I don't know what the reason could be. Perhaps it is the fact that NumVotersIsGreaterEqual runs only on the GPU side, but the parameters in that #ifdef are not taken from the CPU side. I think that this needs a bigger re-write to use Managed Memory.

**Review by fabiencastan — APPROVED** [review]

**Pull request merged**
